import json
import os
import enum
import numpy as np


class EventType(enum.Enum):
    START = 1,
    STOP = 2,
    KILLED = 3,
    CLOSE = 4,
    SEND = 5,
    RECV = 6,
    HAS_DATA = 7,
    SLEEP = 8,
    OUTPUT = 9,
    PROTOCOL_BEGIN = 10,
    PROTOCOL_END = 11
    CANCELLED = 12


## resize a list to accomodate a new index.
def _resize_list(lst, new_size):
    extras = new_size - len(lst) + 1
    lst[len(lst):] = (None for _ in range(extras))
    return lst


## Simulation event.
class Event:
    def __init__(self, typ, ts, md):
        self.typ = EventType[typ]
        self.ts = ts
        self.md = md  # just store the raw json

    def __repr__(self):
        return f'{self.typ}[{self.ts}]'


## Parse a list of events provided as a list of json objects. The list is
## assumed to be the output of the SCL simulator.
def _parse_events(events_json):
    events = list()
    for event in events_json:
        events.append(Event(event['type'], event['timestamp'], event['metadata']))
    return events


## A simulation trace, which is the essentially the list of events generated by
## a particular party in a particular run of the simulated protocol.
class Trace:
    def __init__(self, party_id, events):
        self.party_id = party_id
        self.events = events

    def filter(self, *event_types):
        filterd_events = [e for e in self.events if e.typ not in event_types]
        return Trace(self.party_id, filterd_events);


## Helper object for parsing a trace file as output by
## scl::sim::ManagerWithOutputToStream.
class TraceFile:
    def __init__(self, filename):
        self.filename = filename

    def __enter__(self):
        self.f = open(self.filename, mode='r')
        try:
            self.number_of_parties = int(self.f.readline())
        except ValueError:
            # first line is probably not the number of
            # parties---assume that the filename is "foo_n.trace" and
            # read the number of parties from there.
            self.number_of_parties = int(self.filename.split('.')[0].split('_')[-1])
            self.f.close()
            self.f = open(self.filename, mode='r')

        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.f.close()

    def __iter__(self):
        return self

    def __next__(self):
        line = self.f.readline()

        if line == '':
            raise StopIteration

        ## assumes that the file is well-formed
        data = json.loads(line)
        party_id = data['party_id']
        events = data['trace']  # rename here since events make a bit more sense
        
        return Trace(party_id, _parse_events(events))


## Protocol information.
class Protocol:
    def __init__(self):
        self.execution_time = 0.0
        self.sent = 0
        self.recv = 0
        self.sent_to = list()
        self.recv_from = list()

    def add_sent_to(self, idx, v):
        if len(self.sent_to) <= idx:
            self.sent_to = _resize_list(self.sent_to, idx)
        self.sent_to[idx] = v
        self.sent += v

    def add_recv_from(self, idx, v):
        if len(self.recv_from) <= idx:
            self.recv_from = _resize_list(self.recv_from, idx)
        self.recv_from[idx] = v
        self.recv += v

    def __add__(self, other_protocol):
        self.execution_time += other_protocol.execution_time
        self.sent += other_protocol.sent
        self.recv += other_protocol.recv
        ## TODO: Missing sent_to, recv_from
        
    def __repr__(self):
        return f'<{self.execution_time}, {self.sent}, {self.recv}>'


## Parse a trace into a protocol object
def _parse_protocol(events, protocol_begin_index):

    idx = protocol_begin_index
    if events[idx].typ != EventType.PROTOCOL_BEGIN:
        raise RuntimeError('missing PROTOCOL_BEGIN event')

    protocol = Protocol()
    start_time = events[idx].ts
    name = events[idx].md['name']

    while events[idx].typ != EventType.PROTOCOL_END:

        if events[idx].typ == EventType.SEND:
            to = events[idx].md['channel_id']['remote']
            n = events[idx].md['amount']
            protocol.add_sent_to(to, n)

        elif events[idx].typ == EventType.RECV:
            frm = events[idx].md['channel_id']['remote']
            n = events[idx].md['amount']
            protocol.add_recv_from(frm, n)

        idx += 1

    protocol.execution_time = events[idx].ts - start_time

    return idx, name, protocol


def _trace_incomplete(events, protocol_begin_index):

    idx = protocol_begin_index

    while idx < len(events):
        if events[idx].typ == EventType.PROTOCOL_END:
            return False
        idx += 1

    return True


## Parses a trace into one or more Protocol objects. TODO: Insert validation.
def _parse_protocols(trace, protocols_to_skip):
    
    events = trace.events

    if len(events) == 0:
        print('no events found in trace')
        return dict()
    
    if events[0].typ != EventType.START:
        raise RuntimeError('missing START event')
    
    protocols = dict()
    evidx = 1
    while True:

        # stop when we hit a STOP event
        if events[evidx].typ in (EventType.STOP,
                                 EventType.KILLED,
                                 EventType.CANCELLED):
            break

        # do not parse an incomplete trace.
        if _trace_incomplete(events, evidx):
            break
        
        evidx, name, protocol = _parse_protocol(events, evidx)
        evidx += 1

        if protocols_to_skip is not None and name in protocols_to_skip:
            continue

        if name in protocols:
            protocols[name] += protocol
        else:
            protocols[name] = protocol

    return protocols


def load_trace_from_file(filename, protocols_to_skip=None):
    parties = list()
    with TraceFile(filename) as tf:
        n = tf.number_of_parties
        for trace in tf:

            pid = trace.party_id

            if len(parties) <= pid:
                parties = _resize_list(parties, pid)
                parties[pid] = dict()

            protocols = _parse_protocols(trace, protocols_to_skip)

            for name in protocols:
                if name in parties[pid]:
                    parties[pid][name].append(protocols[name])
                else:
                    parties[pid][name] = [protocols[name]]

    return n, parties


def _get_generic(parties, attr):
    data = dict()

    for i, protocols in enumerate(parties):
        for name in protocols:

            if name not in data:
                data[name] = list()

            if len(data[name]) <= i:
                data[name] = _resize_list(data[name], i)

            data[name][i] = np.array([getattr(p, attr) for p in protocols[name]])


    for name in data:
        data[name] = np.array(data[name], dtype=object)
    
    return data


def get_execution_times(parties):
    return _get_generic(parties, 'execution_time')


def get_total_sent(parties):
    return _get_generic(parties, 'sent')


def get_total_recv(parties):
    return _get_generic(parties, 'recv')


def _get_average_generic(traces, attr, name_filter):
    for t in traces:
        v = _get_generic(t, attr)
        s = np.sum(np.array([v[n] for n in v.keys() if name_filter is
                             None or n in name_filter]), axis=0)
        yield np.average(s, axis=0)


def get_average_sent_all_parties(traces, name_filter=None):
    return np.array(list(_get_average_generic(traces, 'sent', name_filter)))


def get_average_recv_all_parties(traces, name_filter=None):
    return np.array(list(_get_average_generic(traces, 'recv', name_filter)))


def get_average_execution_time_all_parties(traces, name_filter=None):
    return np.array(list(_get_average_generic(traces, 'execution_time', name_filter)))


def load_traces_from_directory(directory, protocols_to_skip=None):
    files = os.listdir(directory)

    traces = list()
    ns = list()

    for f in files:
        n, trace = load_trace_from_file(directory + f, protocols_to_skip)
        traces.append(trace)
        ns.append(n)

    # ensure traces are sorted according to the number of parties
    n, t = zip(*sorted(zip(ns, traces)))
    return np.array(n), t


def get_execution_time_of(traces, protocol_key, party_id = 0):
    et = [get_execution_times(t) for t in traces]
    return np.array([e[protocol_key][party_id] for e in et])


def get_total_sent_of(traces, protocol_key, party_id = 0):
    et = [get_total_sent(t) for t in traces]
    return np.array([e[protocol_key][party_id] for e in et])


def get_total_recv_of(traces, protocol_key, party_id = 0):
    et = [get_total_recv(t) for t in traces]
    return np.array([e[protocol_key][party_id] for e in et])


def get_protocol_names(traces, party_id = None):
    if party_id is None:
        return [list(trace.keys()) for trace in traces]
    else:
        return list(traces[party_id].keys())
